
# Monitor configuration
#monitor=eDP-1,preferred,auto,1

# Mirror Monitor example 
monitor=eDP-1,preferred,auto,1
monitor=,1920x1080,auto,1,mirror,eDP-1
#
# monitor = eDP-1, 1920x1080, 0x0, 1
# monitor = , 1920x1080, 1920x0, 1

# Source a file (multi-file configs)
source = ~/.config/hypr/source/environment.conf
source = ~/.config/hypr/source/binds.conf
source = ~/.config/hypr/source/autostart.conf
source = ~/.config/hypr/source/windowrules.conf
source = ~/.config/hypr/source/input.conf
source = ~/.config/hypr/source/appearance.conf
source = ~/.config/hypr/source/misc.conf
source = ~/.config/hypr/source/plugins.conf


# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
 source = ~/.config/hypr/source/myown.conf

