animations {
    enabled = no # turn on when we want to

    bezier = myBezier, 0.4, 0.0, 0.2, 1.0
    animation = windows, 1, 1, myBezier, popin 80%
    animation = border, 1, 1, myBezier
    animation = fade, 1, 1, myBezier
    animation = workspaces, 1, 1, myBezier, slidefade 20%
}

general {
  gaps_in = 5
  gaps_out = 10
}
