windowrule {
  name = windowrule-1
  float = on
  match:class = ^(org.gnome.Calculator)$
}


# Picture-in-picture
windowrule {
  name = windowrule-2
  float = on
  move = (1492) (839)
  size = 427 240
  pin = on
  match:title = ^(Picture-in-Picture)$
}


# Kitty floating
windowrule {
  name = windowrule-3
  float = on
  match:class = ^(kitty-floating)$
}


# Selection (slurp, grimblast, etc.)
# always off the no_anim for better animation
layerrule=no_anim off, match:class selection

# Idle inhibit when in fullscreen
windowrule {
  name = windowrule-4
  idle_inhibit = on
  fullscreen = on
  match:fullscreen = 1
}


# Audacious
windowrule {
  name = windowrule-5
  # not sure it should be no_rounding = on but it doesnt exist.. maybe it should be off?
  rounding = on
  border_size = 0
  no_shadow = on
  match:class = ^Audacious$
}


