windowrule {
  name = windowrule-1
  float = on
  match:class = ^(org.gnome.Calculator)$
}


# Picture-in-picture
windowrule {
  name = windowrule-2
  float = on
  move = (1492) (839)
  size = 427 240
  pin = on
  match:title = ^(Picture-in-Picture)$
}


# Kitty floating
windowrule {
  name = windowrule-3
  float = on
  match:class = ^(kitty-floating)$
}


# Idle inhibit when in fullscreen
windowrule {
  name = windowrule-4
  idle_inhibit = on
  fullscreen = on
  match:fullscreen = 1
}



